version: "3"

services:

  runtime-setup:
    image: swift-nio-transport-services:22.04-5.8
    build:
      args:
        ubuntu_version: "focal"
        base_image: "swiftlang/swift:nightly-5.8-jammy"

  test:
    image: swift-nio-transport-services:22.04-5.8

  shell:
    image: swift-nio-transport-services:22.04-5.8
