version: "3"

services:

  runtime-setup:
    image: swift-nio-transport-services:18.04-5.3
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.3"

  test:
    image: swift-nio-transport-services:18.04-5.3

  shell:
    image: swift-nio-transport-services:18.04-5.3
