version: "3"

services:

  runtime-setup:
    image: swift-nio-transport-services:20.04-5.6
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.6"

  documentation-check:
    image: swift-nio-transport-services:20.04-5.6

  test:
    image: swift-nio-transport-services:20.04-5.6

  shell:
    image: swift-nio-transport-services:20.04-5.6
